NAME: TESTS

ON: [PUSH, PULL_REQUEST]

JOBS:
  LINT:
    RUNS-ON: UBUNTU-LATEST
    STRATEGY:
      FAIL-FAST: FALSE
      MAX-PARALLEL: 40
      MATRIX:
        CHECK: [STYLE]
        PYTHON-VERSION: [3.7]

    STEPS:
    - USES: ACTIONS/CHECKOUT@V2
    - NAME: SET UP PYTHON ${{ MATRIX.PYTHON-VERSION }}
      USES: ACTIONS/SETUP-PYTHON@V1
      WITH:
        PYTHON-VERSION: ${{ MATRIX.PYTHON-VERSION }}
    - NAME: GET PIP CACHE
      ID: PIP-CACHE
      RUN: |
        PYTHON -C "FROM PIP._INTERNAL.LOCATIONS IMPORT USER_CACHE_DIR; PRINT('::SET-OUTPUT NAME=DIR::' + USER_CACHE_DIR)"
    - NAME: PIP CACHE
      USES: ACTIONS/CACHE@V1
      WITH:
        PATH: ${{ STEPS.PIP-CACHE.OUTPUTS.DIR }}
        KEY: ${{ RUNNER.OS }}-PIP-${{ HASHFILES('**/SETUP.PY') }}
        RESTORE-KEYS: |
          ${{ RUNNER.OS }}-PIP-
    - NAME: INSTALL DEPENDENCIES
      RUN: |
        PIP INSTALL -U BLACK==19.10B0
    - NAME: RUN CHECK
      RUN: |
        BLACK --CHECK .

  TEST:
    RUNS-ON: UBUNTU-LATEST
    STRATEGY:
      FAIL-FAST: FALSE
      MAX-PARALLEL: 40
      MATRIX:
        PYTHON-VERSION: [3.7, 3.8]
        DFFML-VERSION: [MASTER, 0.4.0]

    STEPS:
    - USES: ACTIONS/CHECKOUT@V2
    - NAME: SET UP PYTHON ${{ MATRIX.PYTHON-VERSION }}
      USES: ACTIONS/SETUP-PYTHON@V1
      WITH:
        PYTHON-VERSION: ${{ MATRIX.PYTHON-VERSION }}
    - NAME: GET PIP CACHE
      ID: PIP-CACHE
      RUN: |
        PYTHON -C "FROM PIP._INTERNAL.LOCATIONS IMPORT USER_CACHE_DIR; PRINT('::SET-OUTPUT NAME=DIR::' + USER_CACHE_DIR)"
    - NAME: PIP CACHE
      USES: ACTIONS/CACHE@V1
      WITH:
        PATH: ${{ STEPS.PIP-CACHE.OUTPUTS.DIR }}
        KEY: ${{ RUNNER.OS }}-PIP-${{ HASHFILES('**/SETUP.PY') }}
        RESTORE-KEYS: |
          ${{ RUNNER.OS }}-PIP-
    - NAME: INSTALL DEPENDENCIES
      RUN: |
        SET -X
        PIP INSTALL -U PIP SETUPTOOLS WHEEL
        PIP INSTALL -U "HTTPS://GITHUB.COM/INTEL/DFFML/ARCHIVE/${{ MATRIX.DFFML-VERSION }}.ZIP#EGG=DFFML"
        PIP INSTALL -U .
    - NAME: TEST
      RUN: |
        SET -X
        PYTHON -M UNITTEST DISCOVER -V
